Gwen/Jeff Home Page Frontend
cse110-sp24-group1/cse110-sp24-group1 pull request #59
Opened 2024-05-20 08:38 UTC by Doughster

# Update on Home Page
- [x] Created add new folder and add new note button
- [x] Used flex display
- [x] Left room for nav bar to be implemented
- [x] Created home title and search bar 

# Notes
New folder and new note buttons do not have any functionality because we are waiting for the feature where new note/folder buttons pop up a modal to take user input from that

2024-05-20 18:13 UTC, anshisinghh approved these changes

2024-05-20 18:15 UTC, anshisinghh requested changes
code is good, there does seem to be some merge conflicts, please compare with the frontend branch to resolve those before merging
- the code in global.css already exists in the merge branch so that can be removed

2024-05-20 20:31 UTC, anshisinghh approved these changes
fixed merge conflicts, should be good to merge

2024-05-21 21:41 UTC, kabir-vats approved these changes
Looks good to merge

2024-05-21 21:53 UTC, merged